name: Build Test Extension

on:
  workflow_dispatch:

jobs:
  build:
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.5.0
    with:
      duckdb_version: v1.5.0
      ci_tools_version: v1.5.0
      extension_name: fsquery
